# test suite fails on pytest 3.8.0 and above with internal error
pytest>=4.0.0
pytest-cov>=2.3.1
pytest-xdist>=1.25.0
mock>=2.0.0
matplotlib>=2.0.0
seaborn>=0.7.1
ipython>=5.3.0
notebook>=4.4.1
pandas-datareader>=0.5.0
coveralls